/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CircuitFab.glb --types --output src/components/models/CircuitFab.tsx 
Author: Rowan Design (https://sketchfab.com/rowansreid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/circuit-board-free-download-b918bd8af62d4d7990ee0d52acc07067
Title: Circuit Board (Free Download)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
  }
  materials: {
    color_4634441: THREE.MeshStandardMaterial
    color_1206582: THREE.MeshStandardMaterial
    color_16768282: THREE.MeshStandardMaterial
    color_6383466: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/CircuitFab.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1, 0]}>
            <mesh 
              geometry={nodes.Object_4.geometry} 
              material={materials.color_4634441}
              castShadow
              receiveShadow
            />
            <mesh 
              geometry={nodes.Object_5.geometry} 
              material={materials.color_1206582}
              castShadow
              receiveShadow
            />
            <mesh 
              geometry={nodes.Object_6.geometry} 
              material={materials.color_16768282}
              castShadow
              receiveShadow
            />
            <mesh 
              geometry={nodes.Object_7.geometry} 
              material={materials.color_6383466}
              castShadow
              receiveShadow
            />
          </group>
        </group>
      </group>
    </group>
  )
}

export { Model as CircuitFab }

useGLTF.preload('/models/CircuitFab.glb')
